### PR TITLE
Nice stuff 😉

### PR DESCRIPTION
**Pull request by nagisa**

### CODE REVIEW

**Comment by Manishearth** [comment]
I feel like it makes more sense to allow overriding corpus as a cargo fuzz arg, instead of splicing the extra args. Those should be passed down untouched.

**Comment by nagisa** [comment]
This is somewhat difficult to achieve, because CLI like this:

```
cargo-fuzz run <TARGET> [<FILE>...] -- [<ARGS>...]
```

is not expressible with clap, sadly and

```
cargo-fuzz run <TARGET> [<FILE>...] [<ARGS>...]
```

is obviously ambiguous. We could have a flag that looks like `--no-default-corpus` but I feel like looking at the ARGS to figure if we should pass through our own corpus is trivially enough correct.

**Comment by Manishearth** [comment]
You should have args before target.

This is a pretty common CLI pattern. `cmd <args> <name> -- <...>`

**Comment by nagisa** [comment]
Why are we even travis-ing stable rust?

**Comment by nagisa** [comment]
This is what the CLI looks like now, which is exactly what I was going for

```
    cargo-fuzz run <TARGET> [CORPUS]... [-- <ARGS>...]
```

Couldn’t be any better.

---

> You should have args before target.

That requires either copying the whole set of libfuzzer arguments into our CLI *or* restricting ourselves from adding our own arguments in the future.

**Comment by Manishearth** [comment]
r+

**Comment by nagisa** [comment]
r=Manishearth

**Comment by nagisa** [comment]
bors r=Manishearth

---

you understand this instead maybe?

**Pull request merged**
