### PR TITLE
Indicate trophy case moved to a separate dedicate repository.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
I did this for a couple reasons:

1. It felt a little misplaced to have the trophy case on cargo-fuzz. It's possible to fuzz using libfuzzer _without_ cargo-fuzz, which is what some people have done
2. I wanted a single unified index for all bugs found fuzzing Rust code, so it's easy to find all the previous fuzzing efforts done

**Comment by frewsxcv** [comment]
Also, I already did this for afl.rs:

https://github.com/rust-fuzz/afl.rs/commit/7537c88a6b0397e4f4995c547f94e0492b51a06f

**Comment by Manishearth** [comment]
kinda feel like it's important to show it off on the main repo but w/e

**Pull request merged**
