### PR TITLE
Relax fuzz dir name constraint

### LINKED ISSUE #238: Support for non-standard project directories
`fuzz` is currently the only possible directory name and it would be nice to have something like `cargo fuzz run --path some_fuzz_project_dir someTarget`

### PR DESCRIPTION
**Pull request by c410-f3r**
Fixes #238 

I am not fully aware of the internals of this project and the chosen approach might not be the best. But hey, it is working.

```bash
cargo fuzz run --fuzz-dir some_fuzz_project_dir someTarget
```

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
I like this idea! Will also wait for another maintainer to approve.

**Comment by nagisa** [comment]
SGTM.

**Review by fitzgen — COMMENTED** [review]
These changes look good; thanks! Would you also be interested in adding support for `--fuzz-dir` to all the other subcommands for consistency?

**Comment by c410-f3r** [comment]
Yes but I only ever used `init` and `run` so I don't know which command should receive the additional `fuzz-dir` parameter. Can you make a list? For example:

Comand | Project dir | Fuzz dir
--- | --- | ---
init | X | X
run |  | X
bar |  | 
foo | X |

**Comment by fitzgen** [comment]
I think all subcommands would benefit from a `--fuzz-dir <dir>` flag:

* [ ] `add`
* [ ] `build`
* [ ] `cmin`
* [ ] `coverage`
* [ ] `fmt`
* [ ] `init`
* [ ] `list`
* [X] `run`
* [ ] `tmin`

They all require executing _some_ kind of command inside the (canonically named) `crate/fuzz` directory.

**Comment by c410-f3r** [comment]
ping @fitzgen

**Review by fitzgen — APPROVED** [review]
Looks great! Thanks for adding the flag to all the other subcommands!

**Comment by c410-f3r** [comment]
@fitzgen  Thanks!

If possible, could you guys publish a new version of `libfuzzer` and `cargo-fuzz` on crates.io in the near future?

**Comment by fitzgen** [comment]
Yeah, I have one thing I want to get into `libfuzzer-sys` before the next publish, but I expect I'll have the PR up tomorrow.

**Comment by fitzgen** [comment]
Published!

**Comment by c410-f3r** [comment]
Thank you very much!

**Pull request merged**
