### PR TITLE
Fixes #181 -- use libFuzzer's -fork to implement -j

### LINKED ISSUE #181: --jobs should pass the argument to the fuzzer?
I am fuzzing my project and I noticed that when using parallel fuzzing with `--jobs` the corpus directory is never updated and the fuzzers never print anything but pulse. Not sure if it's an issue with my setup, but when I used `-- -jobs=n` instead of `--jobs` the corpus directory started to get updated fine, and fuzzers do print every type of log in their respective stdout files.

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
@nagisa It looks like you wrote the original version of the parallel fuzzing, because libFuzzer's builtin support had crappy output. The new output is signifcantly improved, any objections to landing this?

**Comment by nagisa** [comment]
Check Cargo.lock back in. Any benefits other than output? What the new output looks like?

**Comment by alex** [comment]
I didn't remove `Cargo.lock`, this reduces the need for tokio which removes a lot of dependencies :-)

The other benefit is that libFuzzer will automatically restart on OOMs and timeouts. Output looks like:

```
     Running `fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse -artifact_prefix=/home/alexgaynor/projects/rust-asn1/fuzz/artifacts/fuzz_asn1_parse/ /home/alexgaynor/projects/rust-asn1/fuzz/corpus/fuzz_asn1_parse -fork=2`
INFO: Seed: 3776502616
INFO: Loaded 1 modules   (10206 inline 8-bit counters): 10206 [0x55a5f3b7d570, 0x55a5f3b7fd4e), 
INFO: Loaded 1 PC tables (10206 PCs): 10206 [0x55a5f3b7fd50,0x55a5f3ba7b30), 
INFO: -fork=2: fuzzing in separate process(s)
INFO: -fork=2: 0 seed inputs, starting to fuzz in /tmp/libFuzzerTemp.414.dir
#24934: cov: 0 ft: 0 corp: 0 exec/s 12467 oom/timeout/crash: 0/0/0 time: 2s job: 1 dft_time: 0
  NEW_FUNC: 0x55a5f3691a70  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x7ba70)
  NEW_FUNC: 0x55a5f36959b0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x7f9b0)
  NEW_FUNC: 0x55a5f3696fb0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x80fb0)
  NEW_FUNC: 0x55a5f3697b30  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x81b30)
  NEW_FUNC: 0x55a5f3699140  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x83140)
  NEW_FUNC: 0x55a5f3699570  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x83570)
  NEW_FUNC: 0x55a5f3699c50  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x83c50)
  NEW_FUNC: 0x55a5f369bd50  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x85d50)
  NEW_FUNC: 0x55a5f369bf60  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x85f60)
  NEW_FUNC: 0x55a5f369d0f0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x870f0)
  NEW_FUNC: 0x55a5f369d460  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x87460)
  NEW_FUNC: 0x55a5f369e920  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x88920)
  NEW_FUNC: 0x55a5f369efc0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x88fc0)
  NEW_FUNC: 0x55a5f369f1f0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x891f0)
  NEW_FUNC: 0x55a5f369f4e0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x894e0)
  NEW_FUNC: 0x55a5f36a1490  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x8b490)
  NEW_FUNC: 0x55a5f37332a0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x11d2a0)
  NEW_FUNC: 0x55a5f3734560  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x11e560)
  NEW_FUNC: 0x55a5f3734f80  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x11ef80)
  NEW_FUNC: 0x55a5f3736920  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x120920)
  NEW_FUNC: 0x55a5f3738160  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x122160)
  NEW_FUNC: 0x55a5f3738490  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x122490)
  NEW_FUNC: 0x55a5f37387c0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x1227c0)
  NEW_FUNC: 0x55a5f3738840  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x122840)
  NEW_FUNC: 0x55a5f3738880  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x122880)
  NEW_FUNC: 0x55a5f3739780  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x123780)
  NEW_FUNC: 0x55a5f3739b80  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x123b80)
  NEW_FUNC: 0x55a5f373c580  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x126580)
  NEW_FUNC: 0x55a5f373d2c0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x1272c0)
  NEW_FUNC: 0x55a5f3740ea0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12aea0)
  NEW_FUNC: 0x55a5f3741ab0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12bab0)
  NEW_FUNC: 0x55a5f3742210  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12c210)
  NEW_FUNC: 0x55a5f37429f0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12c9f0)
  NEW_FUNC: 0x55a5f3742ea0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12cea0)
  NEW_FUNC: 0x55a5f37441c0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12e1c0)
  NEW_FUNC: 0x55a5f3744a40  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12ea40)
  NEW_FUNC: 0x55a5f3745310  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12f310)
  NEW_FUNC: 0x55a5f3745dd0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12fdd0)
  NEW_FUNC: 0x55a5f3746740  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x130740)
  NEW_FUNC: 0x55a5f3748710  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x132710)
  NEW_FUNC: 0x55a5f3749a00  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x133a00)
  NEW_FUNC: 0x55a5f3749f20  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x133f20)
  NEW_FUNC: 0x55a5f3757130  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x141130)
  NEW_FUNC: 0x55a5f3759ea0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x143ea0)
  NEW_FUNC: 0x55a5f379c730  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x186730)
  NEW_FUNC: 0x55a5f3807890  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x1f1890)
  NEW_FUNC: 0x55a5f380e2e0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x1f82e0)
  NEW_FUNC: 0x55a5f380f170  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x1f9170)
  NEW_FUNC: 0x55a5f381fe30  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x209e30)
  NEW_FUNC: 0x55a5f3820260  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20a260)
  NEW_FUNC: 0x55a5f38202e0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20a2e0)
  NEW_FUNC: 0x55a5f38207f0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20a7f0)
  NEW_FUNC: 0x55a5f38209e0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20a9e0)
  NEW_FUNC: 0x55a5f3820ac0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20aac0)
  NEW_FUNC: 0x55a5f3820ed0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20aed0)
  NEW_FUNC: 0x55a5f38216f0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20b6f0)
  NEW_FUNC: 0x55a5f38218c0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20b8c0)
  NEW_FUNC: 0x55a5f3821bd0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x20bbd0)
  NEW_FUNC: 0x55a5f3826a70  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x210a70)
  NEW_FUNC: 0x55a5f3830670  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x21a670)
  NEW_FUNC: 0x55a5f3848610  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x232610)
  NEW_FUNC: 0x55a5f3849000  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x233000)
  NEW_FUNC: 0x55a5f3851e90  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x23be90)
  NEW_FUNC: 0x55a5f38521a0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x23c1a0)
  NEW_FUNC: 0x55a5f38529b0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x23c9b0)
  NEW_FUNC: 0x55a5f38aac20  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x294c20)
  NEW_FUNC: 0x55a5f38abd30  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x295d30)
  NEW_FUNC: 0x55a5f38accd0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x296cd0)
  NEW_FUNC: 0x55a5f38ad950  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x297950)
  NEW_FUNC: 0x55a5f38ad990  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x297990)
  NEW_FUNC: 0x55a5f38adf80  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x297f80)
  NEW_FUNC: 0x55a5f38ae6d0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x2986d0)
  NEW_FUNC: 0x55a5f38aecd0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x298cd0)
  NEW_FUNC: 0x55a5f38af7e0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x2997e0)
  NEW_FUNC: 0x55a5f38b0120  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x29a120)
  NEW_FUNC: 0x55a5f38b29d0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x29c9d0)
#56733: cov: 338 ft: 822 corp: 22 exec/s 10599 oom/timeout/crash: 0/0/0 time: 3s job: 2 dft_time: 0
  NEW_FUNC: 0x55a5f36926d0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x7c6d0)
  NEW_FUNC: 0x55a5f3693cd0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x7dcd0)
  NEW_FUNC: 0x55a5f3694670  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x7e670)
  NEW_FUNC: 0x55a5f3696610  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x80610)
  NEW_FUNC: 0x55a5f3699040  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x83040)
  NEW_FUNC: 0x55a5f36991c0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x831c0)
  NEW_FUNC: 0x55a5f3699470  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x83470)
  NEW_FUNC: 0x55a5f3699820  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x83820)
  NEW_FUNC: 0x55a5f369ca90  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x86a90)
  NEW_FUNC: 0x55a5f369cdc0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x86dc0)
  NEW_FUNC: 0x55a5f369d860  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x87860)
  NEW_FUNC: 0x55a5f369e520  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x88520)
  NEW_FUNC: 0x55a5f369ec10  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x88c10)
  NEW_FUNC: 0x55a5f369ec90  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x88c90)
  NEW_FUNC: 0x55a5f37336b0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x11d6b0)
  NEW_FUNC: 0x55a5f3735400  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x11f400)
  NEW_FUNC: 0x55a5f3739de0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x123de0)
  NEW_FUNC: 0x55a5f3741bb0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12bbb0)
  NEW_FUNC: 0x55a5f3741c70  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12bc70)
  NEW_FUNC: 0x55a5f3741ce0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12bce0)
  NEW_FUNC: 0x55a5f3741f30  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12bf30)
  NEW_FUNC: 0x55a5f3742160  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12c160)
  NEW_FUNC: 0x55a5f37421d0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12c1d0)
  NEW_FUNC: 0x55a5f3742570  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12c570)
  NEW_FUNC: 0x55a5f37427c0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12c7c0)
  NEW_FUNC: 0x55a5f3742e30  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12ce30)
  NEW_FUNC: 0x55a5f3742ec0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12cec0)
  NEW_FUNC: 0x55a5f3742f30  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12cf30)
  NEW_FUNC: 0x55a5f37431d0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12d1d0)
  NEW_FUNC: 0x55a5f3743410  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12d410)
  NEW_FUNC: 0x55a5f37434e0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12d4e0)
  NEW_FUNC: 0x55a5f3743520  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12d520)
  NEW_FUNC: 0x55a5f37437c0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12d7c0)
  NEW_FUNC: 0x55a5f3743a00  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x12da00)
  NEW_FUNC: 0x55a5f374d390  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x137390)
  NEW_FUNC: 0x55a5f374f900  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x139900)
  NEW_FUNC: 0x55a5f3751e70  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x13be70)
  NEW_FUNC: 0x55a5f3754380  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x13e380)
  NEW_FUNC: 0x55a5f37e3c90  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x1cdc90)
  NEW_FUNC: 0x55a5f381e250  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x208250)
  NEW_FUNC: 0x55a5f382f190  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x219190)
  NEW_FUNC: 0x55a5f382f9d0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x2199d0)
  NEW_FUNC: 0x55a5f382fa50  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x219a50)
  NEW_FUNC: 0x55a5f3846c00  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x230c00)
  NEW_FUNC: 0x55a5f3846de0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x230de0)
  NEW_FUNC: 0x55a5f3846fb0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x230fb0)
  NEW_FUNC: 0x55a5f3848e30  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x232e30)
  NEW_FUNC: 0x55a5f384eea0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x238ea0)
#89402: cov: 806 ft: 1457 corp: 55 exec/s 8167 oom/timeout/crash: 0/0/0 time: 6s job: 3 dft_time: 0
#134025: cov: 806 ft: 1495 corp: 56 exec/s 8924 oom/timeout/crash: 0/0/0 time: 8s job: 4 dft_time: 0
#200460: cov: 807 ft: 1498 corp: 57 exec/s 11072 oom/timeout/crash: 0/0/0 time: 12s job: 5 dft_time: 0
#275340: cov: 807 ft: 1498 corp: 57 exec/s 10697 oom/timeout/crash: 0/0/0 time: 15s job: 6 dft_time: 0
#357996: cov: 807 ft: 1498 corp: 57 exec/s 10332 oom/timeout/crash: 0/0/0 time: 20s job: 7 dft_time: 0
  NEW_FUNC: 0x55a5f3695010  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x7f010)
  NEW_FUNC: 0x55a5f36994f0  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x834f0)
  NEW_FUNC: 0x55a5f369db90  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x87b90)
  NEW_FUNC: 0x55a5f3738800  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x122800)
  NEW_FUNC: 0x55a5f374a690  (/home/alexgaynor/projects/rust-asn1/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_asn1_parse+0x134690)
#464296: cov: 836 ft: 1564 corp: 63 exec/s 11811 oom/timeout/crash: 0/0/0 time: 24s job: 8 dft_time: 0
```

**Comment by nagisa** [comment]
works for me I guess.

bors r+

**Pull request merged**
