### PR TITLE
Utilize `eprint` macro where appropriate.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by Manishearth** [comment]
r+

**Comment by frewsxcv** [comment]
bors r=manishearth

**Comment by notriddle** [comment]
LLVM assertions.

*Not* a good sign.

**Comment by frewsxcv** [comment]
@notriddle https://github.com/rust-fuzz/cargo-fuzz/issues/128

**Comment by Manishearth** [comment]
Yeah it's broken on linux rn

**Comment by Manishearth** [comment]
Passes locally on mac.

**Pull request merged**
