### PR TITLE
Support artifact directory

### LINKED ISSUE #6: Set up a corpus and artefact directory
Currently the artefacts are just dumped into the fuzz folder. We should create a corpus dir and pass it to the binary. We should also set up the `-artefact-prefix` arg

http://llvm.org/docs/LibFuzzer.html#options

### PR DESCRIPTION
**Pull request by Manishearth**
(fix #6)

r? @frewsxcv @nagisa

(contains code from other PR since it would be confliciting otherwise)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Seems alright to me. Will wait for @nagisa though

**Comment by nagisa** [comment]
LGTM too.

**Comment by Manishearth** [comment]
Hold on before merging, need to test and tweak.

**Comment by nagisa** [comment]
(again, just like with corpus, we should have a per-fuzz-target subdirectory for these)

**Comment by Manishearth** [comment]
> (again, just like with corpus, we should have a per-fuzz-target subdirectory for these)

I'm not sure if this is necessarily true. Might be better if stuff was shared for the corpus. For artifacts I guess it makes sense. Would be better if done when we figure out how to make libfuzzer run indefinitely, it currently doesn't, so you only have one file to worry about anyway and you can see that in stdlout.

**Pull request merged**
