### PR TITLE
Add script for travis CI test, Fixes #69

### LINKED ISSUE #69: Add proper tests for CI
It should cd to a test crate directory, that contains a single function which panics on an input of size 6 or something, then fuzz init, edit the fuzz target to call this function, run the fuzz target, and ensure a crashfile is produced of the correct length.

### PR DESCRIPTION
**Pull request by ner0x652**

### CODE REVIEW

**Comment by ner0x652** [comment]
I've forgot to remove `fuzz` directory from `testcrate`. I'll push a new commit. Sorry!

**Comment by Manishearth** [comment]
You don't have to close it, just use `git commit --amend` and force-push :smile:

**Comment by Manishearth** [comment]
(or make a new commit and ask me to fix it up for you)

**Comment by ner0x652** [comment]
Thanks, did't know about that :smile:

**Pull request closed without merging**
