### PR TITLE
Changes changes changes

### PR DESCRIPTION
**Pull request by nagisa**
Based on the flag change PR (somebody should merge it already :P)

### CODE REVIEW

**Comment by nagisa** [comment]
Please actually test this out before r+, because I don’t have much stuff to test on, and I saw y'all collecting some stuffs all over the place.

**Comment by Manishearth** [comment]
This works.

**Comment by Manishearth** [comment]
I'm going to do a release

**Comment by Manishearth** [comment]
Oh, shoot, supposed to use bors.

**Pull request merged**
